export const developersData = [
  {
    id: 1,
    name: 'أحمد محمد',
    title: 'مطور واجهات أمامية senior',
    avatar: 'AM',
    location: 'الرياض، السعودية',
    experience: '5 سنوات',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Next.js', 'Redux'],
    bio: 'مطور متخصص في تطوير واجهات المستخدم الحديثة وتجربة المستخدم. خبرة في المشاريع الكبيرة للشركات الرائدة في المنطقة.',
    github: 'github.com/ahmeddev',
    linkedin: 'linkedin.com/in/ahmedmohammed',
    availableForHire: true,
    hourlyRate: '150 - 200 ريال',
    projects: 12,
    rating: 4.8,
    email: 'ahmed@example.com',
    phone: '+966 50 123 4567'
  },
  {
    id: 2,
    name: 'فهد العتيبي',
    title: 'مطور Full Stack',
    avatar: 'FA',
    location: 'دبي، الإمارات',
    experience: '3 سنوات',
    skills: ['Node.js', 'Python', 'MongoDB', 'Docker', 'AWS'],
    bio: 'مطور Full Stack بخبرة في بناء تطبيقات الويب والخدمات الخلفية. متخصص في الحلول السحابية والبنية التحتية.',
    github: 'github.com/fahadalt',
    linkedin: 'linkedin.com/in/fahadalt',
    availableForHire: true,
    hourlyRate: '120 - 180 ريال',
    projects: 8,
    rating: 4.6,
    email: 'fahad@example.com',
    phone: '+971 50 123 4567'
  },
  {
    id: 3,
    name: 'سارة أحمد',
    title: 'مصممة تجربة المستخدم',
    avatar: 'SA',
    location: 'القاهرة، مصر',
    experience: '4 سنوات',
    skills: ['Figma', 'Adobe XD', 'Sketch', 'CSS', 'JavaScript', 'React'],
    bio: 'مصممة تجربة مستخدم بخبرة في تصميم واجهات التطبيقات والمواقع. أركز على التصميم البسيط والسهل في الاستخدام.',
    github: 'github.com/sarahahmed',
    linkedin: 'linkedin.com/in/sarahahmed',
    availableForHire: false,
    hourlyRate: '80 - 120 ريال',
    projects: 15,
    rating: 4.9,
    email: 'sarah@example.com',
    phone: '+20 100 123 4567'
  },
  {
    id: 4,
    name: 'محمد خالد',
    title: 'مهندس DevOps',
    avatar: 'MK',
    location: 'عمان، الأردن',
    experience: '6 سنوات',
    skills: ['Kubernetes', 'Jenkins', 'Terraform', 'Ansible', 'Linux', 'Python'],
    bio: 'مهندس DevOps متخصص في أتمتة العمليات والبنية التحتية. خبرة واسعة في CI/CD وإدارة البنية التحتية السحابية.',
    github: 'github.com/mohammedkhaled',
    linkedin: 'linkedin.com/in/mohammedkhaled',
    availableForHire: true,
    hourlyRate: '200 - 300 ريال',
    projects: 6,
    rating: 4.7,
    email: 'mohammed@example.com',
    phone: '+962 79 123 4567'
  },
  {
    id: 5,
    name: 'نورا علي',
    title: 'مطورة Python',
    avatar: 'NA',
    location: 'المنامة، البحرين',
    experience: '2 سنوات',
    skills: ['Python', 'Django', 'PostgreSQL', 'REST APIs', 'Machine Learning'],
    bio: 'مطورة Python متخصصة في تطوير تطبيقات الويب وخدمات الـ APIs. مهتمة بالذكاء الاصطناعي وتعلم الآلة.',
    github: 'github.com/noorali',
    linkedin: 'linkedin.com/in/noorali',
    availableForHire: true,
    hourlyRate: '100 - 150 ريال',
    projects: 4,
    rating: 4.5,
    email: 'noora@example.com',
    phone: '+973 33 123 4567'
  },
  {
    id: 6,
    name: 'خالد سالم',
    title: 'مطور React Native',
    avatar: 'KS',
    location: 'الدوحة، قطر',
    experience: '3 سنوات',
    skills: ['React Native', 'JavaScript', 'TypeScript', 'Firebase', 'Redux'],
    bio: 'مطور تطبيقات محمولة بخبرة في React Native. عملت على مشاريع للشركات في مختلف القطاعات.',
    github: 'github.com/khaledsalem',
    linkedin: 'linkedin.com/in/khaledsalem',
    availableForHire: false,
    hourlyRate: '130 - 180 ريال',
    projects: 7,
    rating: 4.4,
    email: 'khaled@example.com',
    phone: '+974 66 123 4567'
  }
];
